<?php
require_once '../connect.php';
session_start();

if (!isset($_SESSION['user_id'])) {
    header("Location: ../index.php");
    exit();
}

// Set office_id if not set
if (!isset($_SESSION['office_id'])) {
    $user_id = $_SESSION['user_id'];
    $stmt = $conn->prepare("SELECT office_id FROM users WHERE user_id = ?");
    $stmt->bind_param("i", $user_id);
    $stmt->execute();
    $stmt->bind_result($office_id);
    if ($stmt->fetch()) {
        $_SESSION['office_id'] = $office_id;
    }
    $stmt->close();
}

// Fetch full name
$user_name = '';
$stmt = $conn->prepare("SELECT fullname FROM users WHERE id = ?");
$stmt->bind_param("i", $_SESSION['user_id']);
$stmt->execute();
$stmt->bind_result($fullname);
$stmt->fetch();
$stmt->close();

// Fetch reports
$role = $_SESSION['role'];
if ($role === 'admin') {
    $stmt = $conn->query("
        SELECT gr.*, u.fullname
        FROM generated_reports gr
        JOIN users u ON gr.user_id = u.id
        ORDER BY gr.generated_at DESC
    ");
} else {
    $stmt = $conn->prepare("
        SELECT gr.*, u.fullname
        FROM generated_reports gr
        JOIN users u ON gr.user_id = u.id
        WHERE gr.user_id = ?
        ORDER BY gr.generated_at DESC
    ");
    $stmt->bind_param("i", $_SESSION['user_id']);
    $stmt->execute();
    $stmt = $stmt->get_result();
}
?>

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Generated Reports</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdn.datatables.net/1.13.6/css/dataTables.bootstrap5.min.css" />
    <link href="https://fonts.googleapis.com/css2?family=Poppins&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="css/dashboard.css" />
    <style>
        .table td,
        .table th {
            vertical-align: middle;
        }

        .download-btn {
            background-color: rgb(44, 110, 215);
            color: white;
            padding: 6px 12px;
            text-decoration: none;
            border-radius: 4px;
            transition: background-color 0.3s ease, transform 0.2s ease, box-shadow 0.2s ease;
            display: inline-flex;
            align-items: center;
            gap: 5px;
        }

        .download-btn:hover {
            background-color: rgb(9, 96, 184);
            transform: translateY(-2px);
            box-shadow: 0 4px 10px rgba(0, 0, 0, 0.15);
        }
    </style>
</head>

<body>

    <?php include 'includes/sidebar.php'; ?>

    <div class="main">

        <?php include 'includes/topbar.php'; ?>

        <div class="container-fluid mt-4">
            <div class="card shadow-sm">
                <div class="card-header">
                    <h5 class="mb-0"> Generated Inventory Reports</h5>
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table id="reportsTable" class="table table-striped table-bordered">
                            <thead>
                                <tr>
                                    <th>Filename</th>
                                    <th>Generated By</th>
                                    <th>Date</th>
                                    <th>Download</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php
                                $i = 1;
                                while ($row = $stmt->fetch_assoc()):
                                    $filepath = '../generated_reports/' . $row['filename'];
                                    if (!file_exists($filepath)) continue;
                                ?>
                                    <tr>
                                        <td><?= htmlspecialchars($row['filename']) ?></td>
                                        <td><?= htmlspecialchars($row['fullname']) ?></td>
                                        <td><?= date("M d, Y h:i A", strtotime($row['generated_at'])) ?></td>
                                        <td>
                                            <a class="download-btn btn btn-sm rounded-pill" href="<?= $filepath ?>" target="_blank">
                                                <i class="bi bi-download "></i> Download
                                            </a>
                                        </td>
                                    </tr>
                                <?php endwhile; ?>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>

    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.7.0.min.js"></script>
    <script src="https://cdn.datatables.net/1.13.6/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.13.6/js/dataTables.bootstrap5.min.js"></script>
    <script src="js/dashboard.js"></script>
    <script>
        $(document).ready(function() {
            $('#reportsTable').DataTable();
        });
    </script>

</body>

</html>